COMPILER_TYPE = gnu

CC = gcc

PROG = project
SRCS = main.c timer.c kbd.c utils.c vbe.c graphics.c

CCFLAGS= -Wall -O3

DPADD += ${LIBDRIVER} ${LIBSYS}
LDADD += -llm -ldriver -lsys

LDFLAGS += -L.

MAN=
BINDIR? = /usr/sbin

.include <bsd.prog.mk>
.include <bsd.gcc.mk>